### ISSUE TITLE
Documentation about "Using within the Django admin" is wrong about `embed_settings`

### ISSUE THREAD

**Issue by japsu** [sveetch/djangocodemirror#11]
Hi,

[README](https://github.com/sveetch/djangocodemirror/tree/18bafe533a6d6fea347be784a12a718df2756768#using-within-the-django-admin) suggests the following way of using `djangocodemirror` within the admin site:

```python
class MyModelAdmin(admin.ModelAdmin):
    formfield_overrides = {
        models.TextField: {'widget': CodeMirrorWidget(config_name='default', embed_settings=True)},
    }
```

However, when I try to apply this as follows:

```python
from django.db import models
from django.contrib import admin

from djangocodemirror.fields import CodeMirrorWidget
from reversion.admin import VersionAdmin

from .models import (
    Template,
    StyleSheet,
)


class StyleSheetAdmin(VersionAdmin):
    list_display = ('name', 'active')

    formfield_overrides = {
        models.TextField: {'widget': CodeMirrorWidget(config_name='default', embed_settings=True)},
    }


class TemplateAdmin(VersionAdmin):
    list_display = ('name', 'active')

    formfield_overrides = {
        models.TextField: {'widget': CodeMirrorWidget(config_name='default', embed_settings=True)},
    }


admin.site.register(Template, TemplateAdmin)
admin.site.register(StyleSheet, StyleSheetAdmin)
```

I get the following error:

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/japsu/Hobby/venv-tracontent/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/Users/japsu/Hobby/venv-tracontent/lib/python2.7/site-packages/django/core/management/__init__.py", line 312, in execute
    django.setup()
  File "/Users/japsu/Hobby/venv-tracontent/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/japsu/Hobby/venv-tracontent/lib/python2.7/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/Users/japsu/Hobby/venv-tracontent/lib/python2.7/site-packages/django/contrib/admin/apps.py", line 22, in ready
    self.module.autodiscover()
  File "/Users/japsu/Hobby/venv-tracontent/lib/python2.7/site-packages/django/contrib/admin/__init__.py", line 24, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/Users/japsu/Hobby/venv-tracontent/lib/python2.7/site-packages/django/utils/module_loading.py", line 74, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/japsu/Hobby/tracontent/resources/admin.py", line 21, in <module>
    class TemplateAdmin(VersionAdmin):
  File "/Users/japsu/Hobby/tracontent/resources/admin.py", line 25, in TemplateAdmin
    models.TextField: {'widget': CodeMirrorWidget(config_name='default', embed_settings=True)},
  File "/Users/japsu/Hobby/venv-tracontent/lib/python2.7/site-packages/djangocodemirror/widgets.py", line 28, in __init__
    super(CodeMirrorWidget, self).__init__(attrs=attrs, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'embed_settings'
```

The behaviour is the same using the newest `djangocodemirror` from PyPI or GitHub HEAD. See `models.py` [here](https://github.com/tracon/tracontent/blob/master/resources/models.py).

**Comment by sveetch** [comment]
Yeah 'embed_settings' attribute has been removed since a long time but i forgotted to update the README, in the widget there is some code in its render() method so it should append the settings Javascript code below the textarea HTML.

So you just have to remove `, embed_settings=True` part from Widget usage sample and it should play nice.

**Comment by sveetch** [comment]
It's done since major refactoring with last version from 1.x
