### ISSUE TITLE
RuntimeError: dictionary changed size during iteration

### ISSUE THREAD

**Issue by batisteo** [sveetch/djangocodemirror#19]
I’m working with Django 1.10.7 and Python 3.5

My code:
```python
from djangocodemirror.widgets import CodeMirrorAdminWidget

@admin.register(FlatPage)
class FlatPageAdmin(FlatPageAdmin):
    formfield_overrides = {
        models.TextField: {'widget': CodeMirrorAdminWidget(config_name='html')},
    }
```

```python
Internal Server Error: /admin/flatpages/flatpage/1/change/
Traceback (most recent call last):
  File "/opt/envs/my_project/lib64/python3.5/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/opt/envs/my_project/lib64/python3.5/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/opt/envs/my_project/lib64/python3.5/site-packages/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/envs/my_project/lib64/python3.5/site-packages/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/opt/envs/my_project/lib64/python3.5/site-packages/django/template/response.py", line 109, in render
    self.content = self.rendered_content
  File "/opt/envs/my_project/lib64/python3.5/site-packages/django/template/response.py", line 86, in rendered_content
    content = template.render(context, self._request)
  File "/opt/envs/my_project/lib64/python3.5/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/opt/envs/my_project/lib64/python3.5/site-packages/django/template/base.py", line 208, in render
    return self._render(context)
  File "/opt/envs/my_project/lib64/python3.5/site-packages/django/test/utils.py", line 94, in instrumented_test_render
    return self.nodelist.render(context)
  File "/opt/envs/my_project/lib64/python3.5/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/opt/envs/my_project/lib64/python3.5/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/opt/envs/my_project/lib64/python3.5/site-packages/django/template/loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "/opt/envs/my_project/lib64/python3.5/site-packages/django/test/utils.py", line 94, in instrumented_test_render
    return self.nodelist.render(context)
  File "/opt/envs/my_project/lib64/python3.5/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/opt/envs/my_project/lib64/python3.5/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/opt/envs/my_project/lib64/python3.5/site-packages/django/template/loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "/opt/envs/my_project/lib64/python3.5/site-packages/django/test/utils.py", line 94, in instrumented_test_render
    return self.nodelist.render(context)
  File "/opt/envs/my_project/lib64/python3.5/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/opt/envs/my_project/lib64/python3.5/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/opt/envs/my_project/lib64/python3.5/site-packages/django/template/loader_tags.py", line 70, in render
    result = block.nodelist.render(context)
  File "/opt/envs/my_project/lib64/python3.5/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/opt/envs/my_project/lib64/python3.5/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/opt/envs/my_project/lib64/python3.5/site-packages/django/template/loader_tags.py", line 70, in render
    result = block.nodelist.render(context)
  File "/opt/envs/my_project/lib64/python3.5/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/opt/envs/my_project/lib64/python3.5/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/opt/envs/my_project/lib64/python3.5/site-packages/django/template/defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "/opt/envs/my_project/lib64/python3.5/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/opt/envs/my_project/lib64/python3.5/site-packages/django/template/loader_tags.py", line 210, in render
    return template.render(context)
  File "/opt/envs/my_project/lib64/python3.5/site-packages/django/template/base.py", line 210, in render
    return self._render(context)
  File "/opt/envs/my_project/lib64/python3.5/site-packages/django/test/utils.py", line 94, in instrumented_test_render
    return self.nodelist.render(context)
  File "/opt/envs/my_project/lib64/python3.5/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/opt/envs/my_project/lib64/python3.5/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/opt/envs/my_project/lib64/python3.5/site-packages/django/template/defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "/opt/envs/my_project/lib64/python3.5/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/opt/envs/my_project/lib64/python3.5/site-packages/django/template/defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "/opt/envs/my_project/lib64/python3.5/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/opt/envs/my_project/lib64/python3.5/site-packages/django/template/defaulttags.py", line 315, in render
    return nodelist.render(context)
  File "/opt/envs/my_project/lib64/python3.5/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/opt/envs/my_project/lib64/python3.5/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/opt/envs/my_project/lib64/python3.5/site-packages/django/template/defaulttags.py", line 315, in render
    return nodelist.render(context)
  File "/opt/envs/my_project/lib64/python3.5/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/opt/envs/my_project/lib64/python3.5/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/opt/envs/my_project/lib64/python3.5/site-packages/django/template/base.py", line 1050, in render
    return render_value_in_context(output, context)
  File "/opt/envs/my_project/lib64/python3.5/site-packages/django/template/base.py", line 1028, in render_value_in_context
    value = force_text(value)
  File "/opt/envs/my_project/lib64/python3.5/site-packages/django/utils/encoding.py", line 76, in force_text
    s = six.text_type(s)
  File "/opt/envs/my_project/lib64/python3.5/site-packages/django/utils/html.py", line 391, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
  File "/opt/envs/my_project/lib64/python3.5/site-packages/django/forms/boundfield.py", line 43, in __str__
    return self.as_widget()
  File "/opt/envs/my_project/lib64/python3.5/site-packages/django/forms/boundfield.py", line 101, in as_widget
    return force_text(widget.render(name, self.value(), attrs=attrs))
  File "/opt/envs/my_project/lib64/python3.5/site-packages/djangocodemirror/widgets.py", line 124, in render
    html.append(self.codemirror_script(final_attrs))
  File "/opt/envs/my_project/lib64/python3.5/site-packages/djangocodemirror/widgets.py", line 88, in codemirror_script
    opts = self.codemirror_config()
  File "/opt/envs/my_project/lib64/python3.5/site-packages/djangocodemirror/widgets.py", line 72, in codemirror_config
    return self.editor_manifest.get_codemirror_parameters(self.config_name)
  File "/opt/envs/my_project/lib64/python3.5/site-packages/djangocodemirror/manifest.py", line 220, in get_codemirror_parameters
    for k, v in config.items():
RuntimeError: dictionary changed size during iteration
```

**Comment by sveetch** [comment]
Interesting, are you able to launch tests from tox on python3.5 + django 1.10 ? (this is not related to this specific bug, i'm just curious)

**Comment by batisteo** [comment]
With an hour work, yes!

Shall we drop support for 1.6 and 1.7? https://docs.djangoproject.com/en/stable/internals/release-process/#supported-versions

**Comment by jacob414** [comment]
You probably shouldn't do this, but:
I cheated a problem lite this by `sudo` opening my system Python's `linecache.py`, and replaced `for mod in sys.modules.values():` with `for mod in list(sys.modules.values()):`. It's in `linecache.getlines()`. I've found many places online with people pulling at their hair for this issue (e.g. for `tox`, `tensorflow`)
